project:
  type: book
  preview:
      port: 4200
book:
  title: "Hesaplama Kuramı"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - hafta01.qmd
    - deterministic-finite-automaton-tr.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



